# fonts
font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0

force_ltr no

disable_ligature never

cursor_shape block
cursor_shape_unfocused hollow

cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

scrollbar_handle_opacity 0.0

progress_bar top

window_border_width 2pt
# window_border_radius 2pt
#draw_minimal_borders yes
draw_window_borders_for_single_window no

window_padding_width 10


inactive_text_alpga 0.8

background_opacity 0.6

background_blur 40
active_border_color #00ff00

hide_window_decorations titlebar-only
