-- config imports
require("modules/monitors")
require("modules/programs")
require("modules/autostart")
require("modules/environment")
require("modules/permissions")
require("modules/decorations")
require("modules/animations")
require("modules/misc")
require("modules/input")
require("modules/binds")
require("modules/windowrules")
